CRUD/Models/CUsuario.cs
using System.ComponentModel.DataAnnotations;
using System.Numerics;

namespace CRUD.Models
{
    public class CUsuario
    {
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "DPI")]
        [MinLength(15, ErrorMessage = "El {0} ser mayor a 15 digitos")]
        public string dpi { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Apellido")]
        public string Apellido { get; set;}
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Fecha de Nacimiento")]
        public DateTime FechNac { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Edad")]
        public int edad { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Profesion")]
        public string profesion { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Nacionalidad")]
        public string nacionalidad { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Telefono")]
        public string telefono { get; set;}

        public int resultado { get; set; } = 0;
    }
}

CRUD/Models/EUsuario.cs
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Xml.Linq;

namespace CRUD.Models
{
    public class EUsuario
    {
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "DPI")]
        [MinLength(15, ErrorMessage = "El {0} ser mayor a 15 digitos")]
        public string dpi { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Apellido")]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Fecha de Nacimiento")]
        public DateTime FechNac { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Edad")]
        public int edad { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Profesion")]
        public string profesion { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Nacionalidad")]
        public string nacionalidad { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Telefono")]
        public string telefono { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Usuario Activo")]
        public int sn_activo { get; set; }

    }
}

CRUD/Models/ErrorViewModel.cs
namespace CRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD/Models/cDpi.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace CRUD.Models
{
    public class cDpi
    {
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MinLength(15, ErrorMessage = "El {0} ser mayor a 15 digitos")]
        [Display(Name ="DPI")]
        public string dpi { get; set; }
    }
}

CRUD/Controllers/InicioController.cs
using CRUD.Models;
using CRUD.Servicios;
using Microsoft.AspNetCore.Mvc;

namespace CRUD.Controllers
{
    public class InicioController : Controller
    {
        private readonly IServicioConexion servicioConexion;
        public InicioController(IServicioConexion servicioConexion) 
        {
            this.servicioConexion = servicioConexion;
        }
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(CUsuario usuario)
        {
            if (!ModelState.IsValid)
            {
                return View(usuario);
            }
            await servicioConexion.Crear(usuario);
            if (usuario.resultado == 0)
            {
                ModelState.AddModelError(nameof(usuario.dpi),
                    $"El DPI No.  {usuario.dpi} ya existe.");

                return View(usuario);
            }
            return RedirectToAction("Crear");
        }
        public IActionResult Modificar()
        {
            return View(new cDpi());
        }
        [HttpGet]
        public IActionResult ModificarE(EUsuario usuario)
        {
            return View("ModificarE", usuario);
        }
        [HttpPost]
        public async Task<IActionResult> ModificarEp(EUsuario usuario)
        {
            if (!ModelState.IsValid)
            {
                return View("ModificarE", usuario);
            }
            await servicioConexion.ModUsuario(usuario);
            if (usuario.sn_activo == 0)
            {
                ModelState.AddModelError(nameof(usuario.dpi),
                    $"El DPI No.  {usuario.dpi} ya existe.");

                return View("ModificarE", usuario);
            }
            return View("Modificar");
        }

        [HttpPost]
        public async Task<IActionResult> _ParcialActualizar2(cDpi respuesta)
        { 
            var res = await servicioConexion.BuscarUs(respuesta.dpi);

            if (res)
            {
                var eusuario = await servicioConexion.BuscarU(respuesta.dpi);
                //return PartialView("~/Views/Shared/_ParcialActualizar.cshtml", eusuario);
                //return Ok(eusuario);
                return View("ModificarE", eusuario);
            }
            else
            {
                return View("pError");
            }
     
        }
        public async Task<IActionResult> Desactivar()
        {
            var eusuario = await servicioConexion.EObetener();
            return View(eusuario);
        }
        [HttpPost]
        public async Task<IActionResult> Desactivar([FromBody] string ids)
        {
            await servicioConexion.DesactrivarU(ids);
            return Ok();
        }
        //--------------------
        public async Task<IActionResult> Activar()
        {
            var eusuario = await servicioConexion.EObetener();
            return View(eusuario);
        }
        [HttpPost]
        public async Task<IActionResult> Activar([FromBody] string ids)
        {
            await servicioConexion.ActrivarU(ids);
            return Ok();
        }


        public async Task<IActionResult> Eliminar()
        {
            var eusuario = await servicioConexion.EObetener();
            return View(eusuario);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar([FromBody] string ids)
        {
            await servicioConexion.Eliminar(ids);
            return Ok();
        }

        public IActionResult pError () 
        {
            return View();
        }
    }
}

CRUD/Views/Inicio/Activar.cshtml
@model IEnumerable<EUsuario>;
@{
    ViewData["Title"] = "Desactivar";
}
<div class="m-0 row justify-content-center align-items-center">
    <div class="col-auto text-center">
        <h1 class="bi bi-check2-square">Desactivar</h1>
    </div>
</div>

<div class="m-0 row justify-content-center align-items-center ">
    <div class="card col-auto bg-secondary bg-gradient " style="width: 75rem;">
        <table class="table text-white" id="Activ">
            <thead>
                <tr>
                    <th scope="col">DPI</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Fecha de Nacimiento</th>
                    <th scope="col">Edad</th>
                    <th scope="col">Profesion</th>
                    <th scope="col">Nacionalidad</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Ususario activo</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {


                    <tr data-selected="0">
                        <td>@item.dpi</td>
                        <td>@item.Nombre</td>
                        <td>@item.Apellido</td>
                        <td>@item.FechNac.ToString("dd-MM-yyyy")</td>
                        <td>@item.edad</td>
                        <td>@item.profesion</td>
                        <td>@item.nacionalidad</td>
                        <td>@item.telefono</td>
                        @if (@item.sn_activo == 1)
                        {
                            <td>
                                Activo
                            </td>

                        }
                        else
                        {
                            <td>
                                No activo
                            </td>
                        }
                    </tr>

                }
            </tbody>
        </table>
        <div class="m-0 row justify-content-center align-items-center">
            <button id="btn-activ" class="btn btn-primary col-auto">Activar Ususario</button>
        </div>
    </div>

</div>

@section Scripts{
    <script src="~/js/Activar.js" asp-append-version="true"></script>
    }

CRUD/Views/Inicio/Crear.cshtml
@model CUsuario
@{
    ViewData["Title"] = "Crear";
}
<div class="m-0 row justify-content-center align-items-center">
    <div class="col-auto text-center">
        <h1 class="bi bi-clipboard2-plus-fill">Crear</h1>
    </div>
</div>

<div class="m-0 row justify-content-center align-items-center ">
    <div class="card col-auto bg-secondary bg-gradient " style="width: 60rem;">
        <form class="card-body" asp-action="Crear">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
            <div class="mb-3">
                <label asp-for="dpi" class="form-label"></label>
                <input type="number" asp-for="dpi" class="form-control" autocomplete="off" />
                <span asp-validation-for="dpi" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Nombre" class="form-label"></label>
                <input type="text" asp-for="Nombre" class="form-control" autocomplete="off" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Apellido" class="form-label"></label>
                <input autocomplete="off" type="text" asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="FechNac" class="form-label"></label>
                <input id="fecha" class="form-control" type="date" asp-for="FechNac" />
                <span asp-validation-for="FechNac" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="edad" class="form-label"></label>
                <input id="edad1" type="text" asp-for="edad" class="form-control" autocomplete="off" />
                <span asp-validation-for="edad" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="profesion" class="form-label"></label>
                <input type="text" asp-for="profesion" class="form-control" autocomplete="off" />
                <span asp-validation-for="profesion" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="nacionalidad" class="form-label"></label>
                <input type="text" asp-for="nacionalidad" class="form-control" autocomplete="off" />
                <span asp-validation-for="nacionalidad" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="telefono" class="form-label"></label>
                <input type="number" asp-for="telefono" class="form-control" autocomplete="off" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class=" mb-3 row justify-content-center align-items-center " style="width:100%;" >
                <button id="btn-crear" type="submit" class="btn btn-primary col-auto" style="width:30%;">Enviar</button>
            </div>

        </form>
    </div>
    <partial name="~/Views/Shared/_carga.cshtml" />
    @section Scripts {

        <partial name="_ValidationScriptsPartial" />
    }
</div>

CRUD/Views/Inicio/Desactivar.cshtml
@model IEnumerable<EUsuario>;
@{
    ViewData["Title"] = "Desactivar";
}
<div class="m-0 row justify-content-center align-items-center">
    <div class="col-auto text-center">
        <h1 class="bi bi-check2-square">Desactivar</h1>
    </div>
</div>

<div class="m-0 row justify-content-center align-items-center ">
    <div class="card col-auto bg-secondary bg-gradient " style="width: 75rem;">
        <table class="table text-white" id="desac">
            <thead>
                <tr>
                    <th scope="col">DPI</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Fecha de Nacimiento</th>
                    <th scope="col">Edad</th>
                    <th scope="col">Profesion</th>
                    <th scope="col">Nacionalidad</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Ususario activo</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {


                    <tr data-selected="0">
                        <td>@item.dpi</td>
                        <td>@item.Nombre</td>
                        <td>@item.Apellido</td>
                        <td>@item.FechNac.ToString("dd-MM-yyyy")</td>
                        <td>@item.edad</td>
                        <td>@item.profesion</td>
                        <td>@item.nacionalidad</td>
                        <td>@item.telefono</td>
                        @if (@item.sn_activo == 1)
                        {
                            <td>
                                Activo
                            </td>

                        }
                        else
                        {
                            <td>
                                No activo
                            </td>
                        }
                    </tr>

                }
            </tbody>
        </table>
        <div class="m-0 row justify-content-center align-items-center">
            <button id="btn-desc" class="btn btn-primary col-auto">Desactivar Ususario</button>
        </div>
    </div>

</div>

@section Scripts{
    <script src="~/js/Desactivar.js" asp-append-version="true"></script>
    }

CRUD/Views/Inicio/Eliminar.cshtml
@model IEnumerable<EUsuario>;
@{
    ViewData["Title"] = "Eliminar";
}
<div class="m-0 row justify-content-center align-items-center">
    <div class="col-auto text-center">
        <h1 class="bi bi-trash3">Eliminar</h1>
    </div>
</div>

<div class="m-0 row justify-content-center align-items-center ">
    <div class="card col-auto bg-secondary bg-gradient " style="width: 75rem;">
        <table class="table text-white" id="elim">
            <thead>
                <tr>
                    <th scope="col">DPI</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Fecha de Nacimiento</th>
                    <th scope="col">Edad</th>
                    <th scope="col">Profesion</th>
                    <th scope="col">Nacionalidad</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Ususario activo</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {


                    <tr data-selected="0">
                        <td>@item.dpi</td>
                        <td>@item.Nombre</td>
                        <td>@item.Apellido</td>
                        <td>@item.FechNac.ToString("dd-MM-yyyy")</td>
                        <td>@item.edad</td>
                        <td>@item.profesion</td>
                        <td>@item.nacionalidad</td>
                        <td>@item.telefono</td>
                        @if (@item.sn_activo == 1)
                        {
                            <td>
                                Activo
                            </td>

                        }
                        else
                        {
                            <td>
                                No activo
                            </td>
                        }
                    </tr>

                }
            </tbody>
        </table>
        <div class="m-0 row justify-content-center align-items-center">
            <button id="copy" class="btn btn-primary col-auto">Eliminar</button>
        </div>
    </div>

</div>

    @section Scripts{
        <script src="~/js/eliminar.js" asp-append-version="true"></script>
    }

CRUD/Views/Inicio/Modificar.cshtml
@model cDpi
@{
    ViewData["Title"] = "Modificar";
}

<div class="m-0 row justify-content-center align-items-center">
    <div class="col-auto text-center">
        <h1 class="bi bi-pen">Modificar</h1>
    </div>
</div>

<div class="m-0 mt-3 row justify-content-center align-items-center ">
    <div class="card col-auto bg-secondary bg-gradient " style="width: 60rem;">

        <form class="card-body" asp-action="_ParcialActualizar2">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
            <div class="mb-3">
                <label  class="form-label">Ingrese su DPI </label>
                <input type="number" asp-for="dpi" class="form-control" autocomplete="off" />
                <span asp-validation-for="dpi" class="text-danger"></span>
            </div>

            <div class=" mb-3 row justify-content-center align-items-center " style="width:100%;">
                <button id="btn-mod" class="btn btn-primary col-auto" style="width:30%;" type="submit">Buscar</button>
            </div>
        </form>


    </div>
</div>


<div id="vParcial">
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/Modificar.js" asp-append-version="true"></script>
    <script src="~/js/vistaM.js" asp-append-version="true"></script>
 }

CRUD/Views/Inicio/ModificarE.cshtml
@model EUsuario
@{
    ViewData["Title"] = "Usuario a Modificar";
}
<div class="m-0 row justify-content-center align-items-center">
    <div class="col-auto text-center">
        <h1 class="bi bi-clipboard2-plus-fill">Datos para Actualizar </h1>
    </div>
</div>

<div class="m-0 row justify-content-center align-items-center ">
    <div class="card col-auto bg-secondary bg-gradient " style="width: 60rem;">
        <form class="card-body" asp-action="ModificarEp">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
            <div class="mb-3">
                <label asp-for="dpi" class="form-label"></label>
                <input type="number" asp-for="dpi" class="form-control" autocomplete="off" readonly />
                <span asp-validation-for="dpi" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Nombre" class="form-label"></label>
                <input type="text" asp-for="Nombre" class="form-control" autocomplete="off" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Apellido" class="form-label"></label>
                <input autocomplete="off" type="text" asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="FechNac" class="form-label"></label>
                <input id="fecha1" class="form-control" type="date" asp-for="FechNac" onchange="setEdad()" />
                <span asp-validation-for="FechNac" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="edad" class="form-label"></label>
                <input id="edad2" type="text" asp-for="edad" class="form-control" autocomplete="off" />
                <span asp-validation-for="edad" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="profesion" class="form-label"></label>
                <input type="text" asp-for="profesion" class="form-control" autocomplete="off" />
                <span asp-validation-for="profesion" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="nacionalidad" class="form-label"></label>
                <input type="text" asp-for="nacionalidad" class="form-control" autocomplete="off" />
                <span asp-validation-for="nacionalidad" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="telefono" class="form-label"></label>
                <input type="number" asp-for="telefono" class="form-control" autocomplete="off" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="mb-3" style="display:none;">
                <label asp-for="sn_activo" class="form-label"></label>
                <input type="number" asp-for="sn_activo" class="form-control" autocomplete="off" />
                <span asp-validation-for="sn_activo" class="text-danger"></span>
            </div>
            <div class=" mb-3 row justify-content-center align-items-center " style="width:100%;">
                <button id="btn-crear" type="submit" class="btn btn-primary col-auto" style="width:30%;">Actualizar</button>
            </div>

            <div class=" mb-3 row justify-content-center align-items-center " style="width:100%;">
                <a id="btn-crear"  class="btn btn-dark col-auto" style="width:30%;" asp-action="Modificar"> Cancelar </a>
            </div>

        </form>
    </div>
    <partial name="~/Views/Shared/_carga.cshtml" />
</div>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/Modificar.js" asp-append-version="true"></script>
}

CRUD/Views/Inicio/pError.cshtml
<div class="m-0 mt-5 row justify-content-center align-items-center ">
    <div class="card col-auto bg-warning text-danger" style="width: 60rem;">
        <h1>DPI no existe !!! Ingrese un DPI Correcto</h1>
        <div class="birds">
            <div class="birds__hatdove">
                <div class="birds__hatdove-shadow"></div>
                <div class="birds__hatdove-head">
                    <div class="birds__hatdove-hat"></div>
                    <div class="birds__hatdove-forehead"></div>
                    <div class="birds__hatdove-eye"></div>
                    <div class="birds__hatdove-eye"></div>
                    <div class="birds__hatdove-beak"></div>
                </div>
                <div class="birds__hatdove-backwing"></div>
                <div class="birds__circles-1"></div>
                <div class="birds__hatdove-backleg">
                    <div class="birds__curly"></div>
                </div>
                <div class="birds__hatdove-body"></div>
                <div class="birds__hatdove-frontleg">
                    <div class="birds__curly"></div>
                </div>
                <div class="birds__hatdove-frontwing"></div>
                <div class="birds__circles-2"></div>
                <div class="birds__hatdove-frontwing-finger"></div>
                <div class="birds__hatdove-frontwing-finger"></div>
                <div class="birds__hatdove-frontwing-finger"></div>
            </div>
            <div class="birds__table">
                <div class="birds__table-shadow"></div>
            </div>
            <div class="birds__laptop"></div>
            <div class="birds__laptop">
                <div class="birds__monitor">
                    <div class="birds__code"></div>
                </div>
            </div>
            <div class="birds__coffee"></div>
            <div class="birds__feather"></div>
            <div class="birds__feather"></div>
            <div class="birds__rundove-shadow"></div>
            <div class="birds__rundove">
                <div class="birds__rundove-backwing">
                    <div class="birds__finger"></div>
                    <div class="birds__finger"></div>
                    <div class="birds__finger"></div>
                    <div class="birds__circles"></div>
                </div>
                <div class="birds__rundove-head">
                    <div class="birds__rundove-eye"></div>
                    <div class="birds__rundove-eye"></div>
                    <div class="birds__rundove-beak"></div>
                </div>
                <div class="birds__rundove-backleg">
                    <div class="birds__curly"></div>
                </div>
                <div class="birds__rundove-body"></div>
                <div class="birds__rundove-frontleg">
                    <div class="birds__curly"></div>
                </div>
                <div class="birds__rundove-frontwing">
                    <div class="birds__finger"></div>
                    <div class="birds__finger"></div>
                    <div class="birds__finger"></div>
                    <div class="birds__circles"></div>
                </div>
            </div>
        </div>
        <a class="btn btn-primary" asp-action="Modificar"> Regresar a Busqueda </a>
    </div>
</div>

CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" asp-append-version="true">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" asp-append-version="true" />
</head>
<body class="bg-dark text-white">
    <header>
        <nav class="navbar navbar-expand-sm text-white navbar-toggleable-sm navbar-light bg-primary  box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white bi bi-clipboard2-plus-fill" asp-area="" asp-controller="Inicio" asp-action="Crear">CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white bi bi-pen" asp-area="" asp-controller="Inicio" asp-action="Modificar">Modificar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white bi bi-check2-square" asp-area="" asp-controller="Inicio" asp-action="Desactivar">Desactivar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white bi bi-check2-square" asp-area="" asp-controller="Inicio" asp-action="Activar">Activar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white bi bi-trash3" asp-area="" asp-controller="Inicio" asp-action="Eliminar">Eliminar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()

    <footer class=" footer text-muted">
        <div class="container">
            &copy; 2023 - CRUD - Jose David Ordoñez Lima
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/carga.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>